function selecionar() {
    let select = document.getElementById("select").value
    let formula_a = document.getElementById("formula-a");
    let formula_b = document.getElementById("formula-b");
    let formula_c = document.getElementById("formula-c");
    let formula_xis = document.getElementById("formula-xis");
    let ajuda = document.getElementById("ajuda");
    let botao = document.getElementById("botao");
    let resposta_xis = document.getElementById("resposta-xis");

    if (select == "") {
        ajuda.style.display = "block"
        botao.style.display = "none"
        formula_a.style.display = "none"
        formula_b.style.display = "none"
        formula_c.style.display = "none"
        formula_xis.style.display = "none"
        formula_delta.style.display = "none"
        document.getElementById('b').value = '';
        document.getElementById('c').value = '';
        document.getElementById('delta').value = '';
        document.getElementById('a2').value = '';
        document.getElementById('c2').value = '';
        document.getElementById('delta2').value = '';
        document.getElementById('a3').value = '';
        document.getElementById('b3').value = '';
        document.getElementById('delta3').value = '';
        document.getElementById('a4').value = '';
        document.getElementById('c4').value = '';
        document.getElementById('b4').value = '';
        document.getElementById('b').style.border = "black 1px solid";
        document.getElementById('c').style.border = "black 1px solid";
        document.getElementById('delta').style.border = "black 1px solid";
        document.getElementById('a2').style.border = "black 1px solid";
        document.getElementById('c2').style.border = "black 1px solid";
        document.getElementById('delta2').style.border = "black 1px solid";
        document.getElementById('a3').style.border = "black 1px solid";
        document.getElementById('b3').style.border = "black 1px solid";
        document.getElementById('delta3').style.border = "black 1px solid";
        document.getElementById('a4').style.border = "black 1px solid";
        document.getElementById('b4').style.border = "black 1px solid";
        document.getElementById('c4').style.border = "black 1px solid";


    } else if (select == 'valor-a') {
        ajuda.style.display = "none"
        botao.style.display = "block"
        formula_a.style.display = "block"
        formula_b.style.display = "none"
        formula_c.style.display = "none"
        formula_xis.style.display = "none"
        formula_delta.style.display = "none"
        document.getElementById('b').value = '';
        document.getElementById('c').value = '';
        document.getElementById('delta').value = '';
        document.getElementById('a2').value = '';
        document.getElementById('c2').value = '';
        document.getElementById('delta2').value = '';
        document.getElementById('a3').value = '';
        document.getElementById('b3').value = '';
        document.getElementById('delta3').value = '';
        document.getElementById('a4').value = '';
        document.getElementById('c4').value = '';
        document.getElementById('b4').value = '';
        document.getElementById('b').style.border = "black 1px solid";
        document.getElementById('c').style.border = "black 1px solid";
        document.getElementById('delta').style.border = "black 1px solid";
        document.getElementById('a2').style.border = "black 1px solid";
        document.getElementById('c2').style.border = "black 1px solid";
        document.getElementById('delta2').style.border = "black 1px solid";
        document.getElementById('a3').style.border = "black 1px solid";
        document.getElementById('b3').style.border = "black 1px solid";
        document.getElementById('delta3').style.border = "black 1px solid";
        document.getElementById('a4').style.border = "black 1px solid";
        document.getElementById('b4').style.border = "black 1px solid";
        document.getElementById('c4').style.border = "black 1px solid";

    } else if (select == 'valor-b') {
        ajuda.style.display = "none"
        botao.style.display = "block"
        formula_a.style.display = "none"
        formula_b.style.display = "block"
        formula_c.style.display = "none"
        formula_xis.style.display = "none"
        formula_delta.style.display = "none"
        document.getElementById('b').value = '';
        document.getElementById('c').value = '';
        document.getElementById('delta').value = '';
        document.getElementById('a2').value = '';
        document.getElementById('c2').value = '';
        document.getElementById('delta2').value = '';
        document.getElementById('a3').value = '';
        document.getElementById('b3').value = '';
        document.getElementById('delta3').value = '';
        document.getElementById('a4').value = '';
        document.getElementById('c4').value = '';
        document.getElementById('b4').value = '';
        document.getElementById('b').style.border = "black 1px solid";
        document.getElementById('c').style.border = "black 1px solid";
        document.getElementById('delta').style.border = "black 1px solid";
        document.getElementById('a2').style.border = "black 1px solid";
        document.getElementById('c2').style.border = "black 1px solid";
        document.getElementById('delta2').style.border = "black 1px solid";
        document.getElementById('a3').style.border = "black 1px solid";
        document.getElementById('b3').style.border = "black 1px solid";
        document.getElementById('delta3').style.border = "black 1px solid";
        document.getElementById('a4').style.border = "black 1px solid";
        document.getElementById('b4').style.border = "black 1px solid";
        document.getElementById('c4').style.border = "black 1px solid";

    } else if (select == "valor-c") {
        ajuda.style.display = "none"
        botao.style.display = "block"
        formula_a.style.display = "none"
        formula_b.style.display = "none"
        formula_c.style.display = "block"
        formula_xis.style.display = "none"
        formula_delta.style.display = "none"
        document.getElementById('b').value = '';
        document.getElementById('c').value = '';
        document.getElementById('delta').value = '';
        document.getElementById('a2').value = '';
        document.getElementById('c2').value = '';
        document.getElementById('delta2').value = '';
        document.getElementById('a3').value = '';
        document.getElementById('b3').value = '';
        document.getElementById('delta3').value = '';
        document.getElementById('a4').value = '';
        document.getElementById('c4').value = '';
        document.getElementById('b4').value = '';
        document.getElementById('b').style.border = "black 1px solid";
        document.getElementById('c').style.border = "black 1px solid";
        document.getElementById('delta').style.border = "black 1px solid";
        document.getElementById('a2').style.border = "black 1px solid";
        document.getElementById('c2').style.border = "black 1px solid";
        document.getElementById('delta2').style.border = "black 1px solid";
        document.getElementById('a3').style.border = "black 1px solid";
        document.getElementById('b3').style.border = "black 1px solid";
        document.getElementById('delta3').style.border = "black 1px solid";
        document.getElementById('a4').style.border = "black 1px solid";
        document.getElementById('b4').style.border = "black 1px solid";
        document.getElementById('c4').style.border = "black 1px solid";

    } else if (select == "delta-xis") {
        ajuda.style.display = "none"
        resposta_xis.style.display = "block"
        botao.style.display = "block"
        formula_a.style.display = "none"
        formula_b.style.display = "none"
        formula_c.style.display = "none"
        formula_xis.style.display = "block"
        formula_delta.style.display = "block"
        document.getElementById('b').value = '';
        document.getElementById('c').value = '';
        document.getElementById('delta').value = '';
        document.getElementById('a2').value = '';
        document.getElementById('c2').value = '';
        document.getElementById('delta2').value = '';
        document.getElementById('a3').value = '';
        document.getElementById('b3').value = '';
        document.getElementById('delta3').value = '';
        document.getElementById('a4').value = '';
        document.getElementById('c4').value = '';
        document.getElementById('b4').value = '';
        document.getElementById('b').style.border = "black 1px solid";
        document.getElementById('c').style.border = "black 1px solid";
        document.getElementById('delta').style.border = "black 1px solid";
        document.getElementById('a2').style.border = "black 1px solid";
        document.getElementById('c2').style.border = "black 1px solid";
        document.getElementById('delta2').style.border = "black 1px solid";
        document.getElementById('a3').style.border = "black 1px solid";
        document.getElementById('b3').style.border = "black 1px solid";
        document.getElementById('delta3').style.border = "black 1px solid";
        document.getElementById('a4').style.border = "black 1px solid";
        document.getElementById('b4').style.border = "black 1px solid";
    }
}